INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,6 ,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,7 ,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,3 ,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,5 ,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,1 ,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,2 ,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,4 ,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,8 ,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,9 ,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,10,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,11,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,12,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,13,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,14,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,15,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,16,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,17,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,18,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,19,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,20,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,21,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,22,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,23,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,24,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,25,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,26,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,27,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,28,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,29,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,30,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,31,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,32,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,33,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,34,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,35,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,36,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,37,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,38,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,39,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,40,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,41,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,42,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,43,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,44,'C');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,45,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,46,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,47,'B');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,48,'D');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,49,'A');
INSERT INTO RESULT (RESULT_NUM, YEAR, ID_NUM,GRADE) VALUES ((SELECT NVL(MAX(RESULT_NUM)+1,1) FROM RESULT),2016,50,'C');



































































































